services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - backend-rabbitmq-net

# docker network create backend-rabbitmq-net

networks:
  backend-rabbitmq-net:
    external: true